version: "3"
services:
  jackett:
    restart: unless-stopped
    image: linuxserver/jackett
    environment:
      - PUID=$PGID
      - PGID=$PUID
      - TZ=$PUID
    ports:
      - 9117:9117
    volumes:
      - $BLACK_HOLE_DIR:/downloads
      - $CONFIG_DIR/jackett:/config
  sonarr:
    restart: unless-stopped
    image: linuxserver/sonarr
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    ports:
      - 8989:8989
    volumes:
      - $CONFIG_DIR/sonarr:/config
      - $COMPLETE_DIR/tv:/tv
      - $DOWNLOAD_DIR:/downloads
  radarr:
    restart: unless-stopped
    image: linuxserver/radarr
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    ports:
      - 7878:7878
    volumes:
      - $CONFIG_DIR/radarr:/config
      - $COMPLETE_DIR/movies:/movies
      - $DOWNLOAD_DIR:/downloads
  bazarr:
    restart: unless-stopped
    image: linuxserver/bazarr
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    ports:
      - 6767:6767
    volumes:
      - $CONFIG_DIR/bazarr:/config
      - $COMPLETE_DIR/movies:/movies
      - $COMPLETE_DIR/tv:/tv
      - $SCRIPTS_DIR/bazarr:/scripts
  vpn:
    restart: unless-stopped
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    ports:
      - 8080:8080
    volumes:
      - /dev/net:/dev/net:z
      - $CONFIG_DIR/vpn:/vpn
    command: '-d -f ""'
  qbittorrent:
    restart: unless-stopped
    image: linuxserver/qbittorrent
    network_mode: service:vpn
    environment:
      - WEBUI_PORT=8080
      - PUID=$PGID
      - PGID=$PUID
      - TZ=$TZ
    volumes:
      - $DOWNLOAD_DIR:/downloads
      - $CONFIG_DIR/qbittorrent:/config
      - $BLACK_HOLE_DIR:/watch
    depends_on:
      - vpn
